- hosts: dbservers
  tasks:
    - name: 1.Install MYSQL
      yum:
        name: mariadb-server 
        state: present

    - name: 2.Install the Python MySQL Support Libraries
      yum: pkg=MySQL-python state=latest
    
    - name: 3. Start mysql server and enable it on reboot
      service: name=mariadb state=restarted enabled=true

    - name: 4.Copy file with owner and permissions
      copy:
          src: /root/.my.cnf
          dest: /root

    - name: 5. create user  user/test
      mysql_user:
          host: localhost
          name: archana
          password: archana
          priv: '*.*:ALL,GRANT'
          state: present
    - name: 6.Create a New Test DB called myDB
      mysql_db: 
         name: sncf
         state: present 
         login_user: archana
         login_password: archana

    - name: 7. create user  user/test accessble FROM EVERYWHERE
      mysql_user:
          host: '%'
          name: archana
          password: archana
          priv: 'archana.*:ALL,GRANT'
          state: present

    - name: 8. Copy file train_sql
      copy:
          src: /root/sncf-POIE-projet/dev/train.sql
          dest: /root/train.sql
   
    - name: 9. Import train_sql
      mysql_db:
          state: import
          login_user: archana
          login_password: archana
          name: archana
          target: /root/train.sql

    - name: 10. Install Apache :httpd
      service: name=httpd state=started enabled=yes 
  
    - name: 11.Installing php packages 
      yum:
        name: "{{ item }}"
        state: present
      with_items:
      - php
      - php-mysql
      - php-pdo
      - php-gd
      - php-mbstring

    - name: 12. Status Apache
      service: name=httpd state=started enabled=yes  

    - name: 13. Install Apache2-php5
      package: name=php state=present

    - name: 14. Copy index.php
      sudo: yes
      copy: src=/root/sncf-POIE-projet/dev/index.php dest=/var/www/html/index.php

    - name: 15. Copy param.php
      sudo: yes
      copy: src=/root/sncf-POIE-projet/dev/param.php dest=/var/www/html/param.php









