---
- name: Instal php Apache
  hosts: 10.69.8.161
  tasks:
    - name: 1. Install Apache :httpd
      service: name=httpd state=started enabled=yes 
    - name: Installing php packages 
      yum:
        name: "{{ item }}"
        state: present
      with_items:
      - php
      - php-mysql
      - php-pdo
      - php-gd
      - php-mbstring

    - name: 2. Status Apache
      service: name=httpd state=started enabled=yes  
    - name: 3. Install Apache2-php5
      package: name=php state=present



#
#
#templates/root.cnf.j2
#
#[client]
#user=root
#password={{ mysql_root_pass }}
